name: Main workflow
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: build-matrix
        # Find all leaf level directories and reduce into JSON object
        run: |
          matrix="$(find terraform -mindepth 2 -type d  | cut -c 11- | jq -R '[.]' | jq -sc 'add | {dir: .}')"
          echo "::set-output name=matrix::${matrix}"
  terraform:
    needs:
      - terraform-matrix
    runs-on: ubuntu-18.04
    strategy:
      matrix: ${{ fromJson(needs.terraform-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: asdf setup
        uses: asdf-vm/actions/setup@v1
      - name: asdf install
        working-directory: terraform/${{ matrix.dir }}
        run: |
          asdf plugin-add terraform
          asdf install
          
      - name: Terraform Plan
        id: plan
        working-directory: terraform/${{ matrix.dir }}
        # Follows tips from:
        # https://github.community/t/set-output-truncates-multiline-strings/16852/5
        run: |
          fmt-stdout="$(terraform fmt)"
          fmt-stdout="${fmt-stdout//'%'/'%25'}"
          fmt-stdout="${fmt-stdout//$'\n'/'%0A'}"
          fmt-stdout="${fmt-stdout//$'\r'/'%0D'}"
          fmt-outcome=$([ "$?" == 0 ] && echo "success" || echo "failure")
          
          echo "::set-output name=fmt-stdout::${fmt-stdout}
          echo "::set-output name=fmt-outcome::${fmt-outcome}
          
          plan-stdout="$(terraform plan -no-color -detailed-exitcode)"
          plan-stdout="${plan-stdout//'%'/'%25'}"
          plan-stdout="${plan-stdout//$'\n'/'%0A'}"
          plan-stdout="${plan-stdout//$'\r'/'%0D'}"
          echo "::set-output name=plan-stdout::${plan-stdout}"
        continue-on-error: true
      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### \`${{ matrix.dir }}\`
            #### terraform fmt: \`${{ steps.plan.outputs.fmt-outcome }}\`
            <details><summary>Show fmt</summary>

            \`\`\`
            ${{ steps.plan.outputs.fmt-stdout }}
            \`\`\`

            </details>
            
            \`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
