name: Main workflow
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: build-matrix
        # Find all leaf level directories and reduce into JSON object
        run: |
          matrix="$(find helmfile -mindepth 2 -type d  | cut -c 11- | jq -R '[.]' | jq -sc 'add | {dir: .}')"
          echo "::set-output name=matrix::${matrix}"
  helmfile:
    needs:
      - matrix
    runs-on: ubuntu-18.04
    strategy:	
      matrix: ${{ fromJson(needs.terraform-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - name: asdf setup	
        uses: asdf-vm/actions/setup@v1	
      - name: asdf install	
        working-directory: helmfile/${{ matrix.dir }}	
        run: |	
          asdf plugin-add helmfile	
          asdf plugin-add helm
          asdf install
          helm plugin install https://github.com/databus23/helm-diff --version v3.1.2
      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
      - uses: iStreamPlanet/github-actions/helmfile-actions@1b9eef1
        if: github.event_name == 'pull_request'
        with:
          command: diff
