name: Main workflow
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: build-matrix
        # Find all leaf level directories and reduce into JSON object
        run: |
          matrix="$(find terraform -mindepth 2 -type d  | cut -c 11- | jq -R '[.]' | jq -sc 'add | {dir: .}')"
          echo "::set-output name=matrix::${matrix}"
  terraform:
    needs:
      - terraform-matrix
    runs-on: ubuntu-18.04
    strategy:
      matrix: ${{ fromJson(needs.terraform-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: asdf setup
        uses: asdf-vm/actions/setup@v1
      - name: asdf install
        working-directory: terraform/${{ matrix.dir }}
        run: |
          asdf plugin-add terraform
          asdf install
          
      - name: terraform init
        working-directory: terraform/${{ matrix.dir }}
        run: terraform init
      - name: Terraform Plan.
        uses: abatilo/terraform-composite-action@v4
        id: plan
    
