name: Main workflow
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  helmfile:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: asdf setup	
        uses: asdf-vm/actions/setup@v1	
      - name: asdf install	
        working-directory: helmfile/
        run: |	
          mkdir -p $HOME/.helm/plugins
          asdf plugin-add helmfile	
          asdf plugin-add helm
          asdf install
          helm plugin install https://github.com/databus23/helm-diff --version v3.1.2
      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
      - name: "helmfile diff no PR output"
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: helmfile/
        run: |
          asdf current
          helm version
          pwd
          ls -la
          which helmfile
          helmfile list
