name: Main workflow
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: build-matrix
        # Find all leaf level directories and reduce into JSON object
        run: |
          matrix="[{\"name\":\"Checkout\",\"uses\":\"actions/checkout@v2\"},{\"name\": \"Say hello\",\"run\": \"echo hello\"}]"
          echo "::set-output name=matrix::${matrix}"
  terraform:
    needs:
      - terraform-matrix
    runs-on: ubuntu-18.04
    steps:
      ${{ fromJson(needs.terraform-matrix.outputs.matrix) }}
