name: Main workflow
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  install_tools:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: asdf_install
        uses: asdf-vm/actions/install@v1
      - id: terraform-plan
        # Follows tips from:
        # https://github.community/t/set-output-truncates-multiline-strings/16852/5
        run: |
          terraform init
          RAW_PLAN="$(terraform plan -no-color)"
          RAW_PLAN="${RAW_PLAN//'%'/'%25'}"
          RAW_PLAN="${RAW_PLAN//$'\n'/'%0A'}"
          RAW_PLAN="${RAW_PLAN//$'\r'/'%0D'}"
          echo "::set-output name=plan::${RAW_PLAN}"
      - env:
          PLAN: ${{ steps.terraform-plan.outputs.plan }}
        run: |
          echo "${PLAN}"
      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: ${{ steps.terraform-plan.outputs.plan }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Plan 📖\`${{ steps.terraform-plan.outcome }}\`

            <details>
            <summary>Show Plan</summary>
            \`\`\`${process.env.PLAN}\`\`\`
            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
