name: Main workflow
on:
  - push

jobs:
  install_tools:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: asdf_install
        uses: asdf-vm/actions/install@v1
      - id: terraform-plan
        run: |
          terraform init
          echo "::set-output name=plan::$(terraform plan)"
      - env:
          PLAN: ${{ steps.terraform-plan.outputs.plan }}
        run: |
          echo ${PLAN}
